### ISSUE TITLE
[004] Image Loading and Caching Library

### ISSUE THREAD

**Issue by mydamyda** [AndroidDeepDive/Study#13]
- Picasso
- Glide
- Coil

**Comment by mydamyda** [comment]
https://proandroiddev.com/coil-vs-picasso-vs-glide-get-ready-go-774add8cfd40

**Comment by mydamyda** [comment]
https://jizard.tistory.com/224

**Comment by HeesungB** [comment]
https://gun0912.tistory.com/19

**Comment by mydamyda** [comment]
https://coil-kt.github.io/coil/migrating/

**Comment by mydamyda** [comment]
이미지 라이브러리 분석을 할 일보다는, 가져가 쓰는 경우가 많다. 알고 써보자.

**Comment by mydamyda** [comment]
이미지 렌더링 속도
자동 리사이즈 추천

**Comment by mydamyda** [comment]
어떤경우엔 어떤 라이브러리가 좋은가? 고민해보기
