### ISSUE TITLE
003. UI 렌더링 최적화

### ISSUE THREAD

**Issue by mydamyda** [AndroidDeepDive/Study#5]

**Comment by SODA1127** [comment]
4월 29일 목요일 스터디 주제로 선정

**Comment by SODA1127** [comment]
[Introduce Android View Processing & GPU Rendering Profiling 🔍 - 스터디용.pdf](https://github.com/AndroidDeepDive/Study/files/6398718/Introduce.Android.View.Processing.GPU.Rendering.Profiling.-.pdf)

**Comment by SODA1127** [comment]
5월 6일 회의를 통해 나온 정리안

## 전체적인 ToC

### 안드로이드 뷰 렌더링 방식 (기정, 남훈, 세희)

- 오픈소스 레벨
  - Measure Pass
  - Layout Pass
  - View LifeCycle
  - View를 그리는 방법
  - Rendering
- 어플리케이션 레벨에서만 다뤄보는 것으로
  - 예제는 리스트업..

### 프로파일링 (소영, 시영)

- Overdraw 디버깅
- View Rendering Profiling
  - FPS => GPU Profiling 막대 구성요소 별 측정
  - VSync 파보기..(추가돼야 할 내용)
- Performance Profiling => Rendering 관련 내용만 필터링하여 모니터링하는 것으로

### 렌더링 최적화 기법 (기정, 남훈, 희성)

- UI를 많이 그리게 되는 원인
  - 버벅거림을 유발할 수 있는 요소들

- 오버드로잉 방지
- UI 구조 최적화

- 예제를 직접 만들어서 공유

**Comment by SODA1127** [comment]
5월 13일 회의를 통해 나온 정리안

### 결론

모두가 주제에대해서 바운더리는 어렵지 않은 수준으로 정리해볼 수 있었고, 다만 아쉬운 부분은 성능적인 측정을 실제 기기 / 에뮬레이터로 비교해서 하기가 어려웠다.

5월 20일까지 추가로 실제 어플리케이션 레벨에서 UI를 그릴 때 성능측정을 해보고, 비교한 값을 수치화해서 글로 정리해보자.

**Comment by HeesungB** [comment]
- Layout Inspector, DecorView 관련 내용 추가
 -예시 프로파일링 수치 측청

**Comment by nurisis** [comment]
* 실제로 오버드로가 뷰 렌더링에 얼마나 악영향(?)을 미치는지 성능 측정
* Systrace 를 사용한 성능 측정

**Comment by mydamyda** [comment]
- display 상에서의 뷰 렌더링 프로세스
