### ISSUE TITLE
Jetpack Compose 동작 원리 분석하기 

### ISSUE THREAD

**Issue by mydamyda** [AndroidDeepDive/Study#7]

**Comment by mydamyda** [comment]
https://namhoon.kim/2021/03/14/android_deep_dive/001/

**Comment by mcsys** [comment]
https://sysys.medium.com/jetpack-compose-%EC%B2%B4%ED%97%98%EA%B8%B0-8f90aff89f47

**Comment by mydamyda** [comment]
hello world 텍스트뷰만 추가한 상태에서 generated code 분석해보기 (re-mapping level)
샘플 중에 하나 정해서 같이 파보기
Pure DI : Provider를 개발해서 IoC를 구현해본다.

**Comment by SODA1127** [comment]
https://soda1127.github.io/introduce-jetpack-compose/
